### ISSUE TITLE
Random Announcers

### ISSUE THREAD

**Issue by JamesBach93** [Matt-MX/AnnouncerVelocity#1]
Hey,

is it Possible to add Random Announcers in the config ?

So all Announcer with "delay: random" are randomly pick with an custom Timer.

Config:
Random Announcer: true
Random Timer: 600 (time in seconds)

**Comment by JamesBach93** [comment]
Uff wrong section.. have clicked on "[Request Feature]"
Should in "Pull requests". Pls move if possible.

**Comment by Matt-MX** [comment]
Great suggestion, I'll look into implementing this tomorrow.

**Comment by Matt-MX** [comment]
Ability to have a random announcement (between a range) added as of v1.2.1
