### ISSUE TITLE
Loop through a list of broadcasts

### ISSUE THREAD

**Issue by LurgenAU** [Matt-MX/AnnouncerVelocity#2]
It would be handy to be able to add broadcasts to a "group", and have it cycle through them in order. That way you could have a series of messages sent to players, at a pre-defined interval. For bonus points, allow randomisation within the list, so when enabled the list cycles randomly through a selection of notifications.

BTW, fantastic plugin, really great work.

**Comment by Matt-MX** [comment]
Adding in long overdue rework
